name: Bug Report
description: Report a bug in the Better Potions mod
body:
- type: markdown
  attributes:
    value: |
      ## Is there an existing issue for this?
      Please double check if there's already an issue for the bug you encountered. If there is, add any additional information you may have to that issue instead of creating a new one
- type: dropdown
  attributes:
    label: Version
    description: What version of tModLoader are you using?
    multiple: false
    options:
      - Latest 1.4-stable
      - Latest 1.4-preview
    validations: 
      required: true
- type: dropdown
  attributes:
    label: OS
    description: What OS are you using?
    multiple: false
    options:
      - Windows
      - Max
      - Linux
    validations:
      required: true
- type: textarea
  attributes:
    label: Description
    id: description
    description: |
      Describe your issue(s) here. What is the issue?
      Please keep this as concise as possible, preferable a single line just describing the issue
      For example: "When I press X button in menu Y, the component Z becomes unclickable"
- type: textarea
  attributes:
    label: Log File
    description: |
      Please attach the `client.log` file here. You'll find the log files in the logs folder. Look for the `client.log` file.
      On the 1.4 versions it can be found in the "tModLoader-Logs" folder in your tModLoader install directory (to find your install directory on Steam right click on tModloader, then Manage and "Browse local files") 
      
      In 1.3 it can be found in the following folders:
      Windows Logs: `C:\Documents\My Games\Terraria\ModLoader\Logs`
      Linux Logs: `~/.local/share/Terraria/ModLoader/Logs/` or `$XDG_DATA_HOME/Terraria/ModLoader/Logs/`
      Mac Logs: `~/Library/Application support/Terraria/ModLoader/Logs/`
      
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please describe the steps to reproduce this issue
    placeholder: |
      1. [First Step]
      2. [Second Step]
      3. [And so on...]
- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      What should be happening? If you don't know, leave what you think should happen
- type: textarea
  attributes:
    label: Actual Behavior
    description: |
      What is actually happening?
- type: textarea
  attributes:
    label: Reproduction frequency
    description: |
      How often are you reliably able to reproduce this issue?
- type: textarea
  attributes:
    label: Additional Information
    description: |
       Any additional information, configuration, or data that might be necessary to reproduce the issue.
